# Generated by Django 5.1.4 on 2024-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullsail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/%y')),
            ],
        ),
        migrations.CreateModel(
            name='oregonstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/%y')),
            ],
        ),
        migrations.CreateModel(
            name='saintlouis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/%y')),
            ],
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='coloradostate',
        ),
    ]
